# <font face="times"><font size="6pt"><p style = 'text-align: center;'><b>Computational Social Science</b><br/><br/>
<font face="times"><font size="6pt"><p style = 'text-align: center;'><b> K-Nearest Neighbors Algorithm</b><br/><br/>








## For the following questions, you'll need to find your own data. 

## Describe what the data are and what variables you'll be using. 

# The Data that I will be using in my analysis is medical data for Pima Indian Women as it relates to factors that contribute to the likelihood of having diabetes

In [1]:
pwd

'/Users/marvinwilliams/Documents/Authorized Personnel Only/Grad School/DATA 765 -  Computational Social Science/Lesson 6'

In [2]:
cd "Data"

[Errno 2] No such file or directory: 'Data'
/Users/marvinwilliams/Documents/Authorized Personnel Only/Grad School/DATA 765 -  Computational Social Science/Lesson 6


In [19]:
ls

blockbusters.csv  diabetes2.csv  Ps4GamesSales.csv
chinook.db        FirstData.csv  videogamesales.csv


In [20]:
diabetes = pd.read_csv("diabetes2.csv")

### Looking at vairables including Glucose, Insulin, BMI, Diabetes Pedigree Function, and Age, I will predict the likelihood of having diabetes based on these factors. 

In [21]:
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [22]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
X = diabetes[['Glucose', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]

In [24]:
y = diabetes['Outcome']

***
***
# Import all of the modules you'll be using here:

In [25]:
import pandas as pd

In [26]:
import numpy as np

In [27]:
import matplotlib.pyplot as plt

In [28]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
from sklearn.metrics import classification_report, confusion_matrix as cm

In [31]:
from sklearn import metrics

In [59]:
from sklearn.svm import SVC

***
***


# Question 1 of 5  [2 Marks]

## Find a dataset and run your own `KNN`, using a value of K=10. 

## Be sure to create training and testing sets of data. 

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y, random_state = 0)

In [35]:
db = KNeighborsClassifier(n_neighbors = 10)

In [36]:
db.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [37]:
db.score(X_test, y_test)

0.7604166666666666

In [38]:
db_pred = db.predict(X_test)

In [39]:
print("Neighbors accuracy:", metrics.accuracy_score(y_test, db_pred))
print("precision:", metrics.precision_score(y_test, db_pred, average='weighted'))

Neighbors accuracy: 0.7604166666666666
precision: 0.7508573914823914


In [43]:
cm(db_pred, y_test)

array([[116,  32],
       [ 14,  30]])

***
***

# Question 2 of 5  [2 Marks]

## Run KNNs using the data you found in Question 1 and use GridSearch to find the optimal value of `K`. Which `K` worked best?

## Calculate the precision and accuracy for this `K`. How does it compare to a `K` of 10?

## Interpret these results. What do you see?

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y, random_state = 0)

In [45]:
dbknn = KNeighborsClassifier()

In [46]:
para = {'n_neighbors': range(1,11)}

In [47]:
db_GS = GridSearchCV(dbknn, para, cv = 5)

In [48]:
db_GS.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None, param_grid={'n_neighbors': range(1, 11)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [49]:
pd.DataFrame(db_GS.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.005386      0.002529         0.008919        0.000488   
1       0.004916      0.001605         0.013452        0.004388   
2       0.003903      0.000128         0.009076        0.000279   
3       0.003936      0.000111         0.010010        0.001333   
4       0.003531      0.000688         0.007280        0.001466   
5       0.002211      0.000051         0.005134        0.000031   
6       0.002203      0.000017         0.005079        0.000048   
7       0.002177      0.000022         0.006126        0.001239   
8       0.002184      0.000033         0.005180        0.000089   
9       0.002232      0.000052         0.005136        0.000050   

  param_n_neighbors               params  split0_test_score  \
0                 1   {'n_neighbors': 1}           0.715517   
1                 2   {'n_neighbors': 2}           0.706897   
2                 3   {'n_neighbors': 3}           0.698276   
3                 4   {'n_neighbors': 4}           0.672414   
4                 5   {'n_neighbors': 5}           0.724138   
5                 6   {'n_neighbors': 6}           0.706897   
6                 7   {'n_neighbors': 7}           0.706897   
7                 8   {'n_neighbors': 8}           0.706897   
8                 9   {'n_neighbors': 9}           0.715517   
9                10  {'n_neighbors': 10}           0.706897   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.660870           0.669565           0.686957           0.695652   
1           0.713043           0.713043           0.643478           0.686957   
2           0.686957           0.704348           0.686957           0.686957   
3           0.730435           0.721739           0.652174           0.721739   
4           0.721739           0.756522           0.686957           0.739130   
5           0.747826           0.756522           0.695652           0.765217   
6           0.747826           0.773913           0.704348           0.773913   
7           0.739130           0.782609           0.695652           0.747826   
8           0.721739           0.747826           0.678261           0.747826   
9           0.730435           0.756522           0.686957           0.739130   

   mean_test_score  std_test_score  rank_test_score  
0         0.685764        0.019344               10  
1         0.692708        0.026385                8  
2         0.692708        0.007287                8  
3         0.699653        0.031360                7  
4         0.725694        0.023000                4  
5         0.734375        0.027846                2  
6         0.741319        0.030728                1  
7         0.734375        0.030928                2  
8         0.722222        0.025626                6  
9         0.723958        0.024454                5

In [50]:
alist = [10,7]

In [51]:
for a in alist:
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
    dbknnchk = KNeighborsClassifier(n_neighbors = a)
    dbknnchk.fit(X, y)
    db_newpred = dbknnchk.predict(X_test)
    confused = cm(db_newpred, y_test)
    print(str(a), "Neighbors accuracy:", metrics.accuracy_score(y_test, db_newpred))
    print("precision:", metrics.precision_score(y_test, db_newpred, average='weighted'))
    print(confused)

10 Neighbors accuracy: 0.8072916666666666
precision: 0.8025471552257267
[[118  25]
 [ 12  37]]
7 Neighbors accuracy: 0.8177083333333334
precision: 0.8136297565721008
[[117  22]
 [ 13  40]]


### The results from the GridSearch show us the optimal K for our model is 7, with the highest mean test score, yielding more precise and accurate results than our model with a K of 10


***
***

# Question 3 of 5  [2 Marks]

##  Using your data, run an SVM model. 

In [52]:
svc = SVC(kernel = 'linear')

In [53]:
svc.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

***
***

# Question 4 of 5  [2 Marks]

## For the SVM model you ran in Question 3, calculate the precision and accuracy. 

## How does this compare to the KNN models you just ran?

## How do you interpret these SVM results?


In [54]:
db_pred2 = svc.predict(X_test)

In [55]:
print("Accuracy: ", metrics.accuracy_score(db_pred2, y_test))
print("Precision: ", metrics.precision_score(db_pred2, y_test))

Accuracy:  0.7864583333333334
Precision:  0.5806451612903226


In [56]:
cm(db_pred2, y_test)

array([[115,  26],
       [ 15,  36]])

### The results from the SVM correctly classified 79% of our sample as having diabetes, with only  < 3% accuracy than our KNN model with a K of 7. Our SVM is less accurate than our KNN however, as it was only able to  The precision for our SVC was significantly lower than our KNN, about 23% less precise, with a 58% precision rate, meaning although our model yielded accurate results, the reliabililty for our model is much lower than our KNN model. 

***
***

# Question 5 of 5  [2 Marks]

## Using your SVM and the function from the Lesson 06 lecture, plot the support vectors. 

## What do you see here?

### ??? Couldn't understand how to use this function

In [60]:
def plot_svc_decision_function(svc):
    """Plot the decision function for a 2D SVC"""
    x = np.linspace(plt.xlim()[0], plt.xlim()[1], 30)
    y = np.linspace(plt.ylim()[0], plt.ylim()[1], 30)
    Y, X = np.meshgrid(y, X)
    P = np.zeros_like(X)
    for i, xi in enumerate(X):
        for j, yj in enumerate(y):
            P[i, j] = clf.decision_function([[xi, yj]])
    return plt.contour(X, Y, P, 
                       colors='k',
                       levels=[-1, 0, 1],
                       linestyles=['--', '-', '--'])

In [62]:
plt.figure()
plt.scatter(X[:, 0], X[:, 1], c=y)
plot_svc_decision_function(svc);

TypeError: '(slice(None, None, None), 'Age')' is an invalid key

<Figure size 432x288 with 0 Axes>