# <font face="times"><font size="6pt"><p style = 'text-align: center;'><b>Computational Social Science</b><br/><br/>
<font face="times"><font size="6pt"><p style = 'text-align: center;'><b> K-Nearest Neighbors Algorithm</b><br/><br/>








## The Data that I will be using in my analysis is medical data for Pima Indian Women as it relates to factors that contribute to a higher likelihood of having diabetes

***
## Importing all of the modules being used here:

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
from sklearn.metrics import classification_report, confusion_matrix as cm

In [7]:
from sklearn import metrics

In [8]:
from sklearn.svm import SVC

***
## Load Data and Assign appropiate variables

In [9]:
pwd

'/Users/marvinwilliams/Documents/Gitstuff/KNN - Python'

In [10]:
ls

KNN Notebook.ipynb  diabetes2.csv


In [11]:
diabetes = pd.read_csv("diabetes2.csv")

### Looking at vairables including Glucose, Insulin, BMI, Diabetes Pedigree Function, and Age, I will predict the likelihood of having diabetes based on these factors. 

In [12]:
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [13]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [14]:
X = diabetes[['Glucose', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]

In [15]:
y = diabetes['Outcome']

***
***

## Runnnig a `KNN`, using a value of K=10. 

## Creatig training and testing sets of data. 

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y, random_state = 0)

In [17]:
db = KNeighborsClassifier(n_neighbors = 10)

In [18]:
db.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [19]:
db.score(X_test, y_test)

0.7604166666666666

In [20]:
db_pred = db.predict(X_test)

In [21]:
print("Neighbors accuracy:", metrics.accuracy_score(y_test, db_pred))
print("precision:", metrics.precision_score(y_test, db_pred, average='weighted'))

Neighbors accuracy: 0.7604166666666666
precision: 0.7508573914823914


In [22]:
cm(db_pred, y_test)

array([[116,  32],
       [ 14,  30]])

***
***


## Run KNNs using the data from above and use GridSearch to find the optimal value of `K`. 

## Calculate the precision and accuracy for this `K` and how it compares to a `K` of 10


In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y, random_state = 0)

In [24]:
dbknn = KNeighborsClassifier()

In [25]:
para = {'n_neighbors': range(1,11)}

In [26]:
db_GS = GridSearchCV(dbknn, para, cv = 5)

In [27]:
db_GS.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 11)})

In [28]:
pd.DataFrame(db_GS.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.004173      0.000753         0.008380        0.001649   
1       0.003107      0.000706         0.009019        0.003865   
2       0.002212      0.000215         0.004699        0.000251   
3       0.002243      0.000357         0.004929        0.000323   
4       0.002030      0.000072         0.004519        0.000123   
5       0.001947      0.000051         0.004550        0.000216   
6       0.001918      0.000027         0.004379        0.000055   
7       0.001980      0.000081         0.004406        0.000060   
8       0.001922      0.000014         0.004451        0.000074   
9       0.001966      0.000048         0.004506        0.000085   

  param_n_neighbors               params  split0_test_score  \
0                 1   {'n_neighbors': 1}           0.715517   
1                 2   {'n_neighbors': 2}           0.706897   
2                 3   {'n_neighbors': 3}           0.698276   
3                 4   {'n_neighbors': 4}           0.672414   
4                 5   {'n_neighbors': 5}           0.724138   
5                 6   {'n_neighbors': 6}           0.706897   
6                 7   {'n_neighbors': 7}           0.706897   
7                 8   {'n_neighbors': 8}           0.706897   
8                 9   {'n_neighbors': 9}           0.715517   
9                10  {'n_neighbors': 10}           0.706897   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.660870           0.669565           0.686957           0.695652   
1           0.713043           0.713043           0.643478           0.686957   
2           0.686957           0.704348           0.686957           0.686957   
3           0.730435           0.721739           0.652174           0.721739   
4           0.721739           0.756522           0.686957           0.739130   
5           0.747826           0.756522           0.695652           0.765217   
6           0.747826           0.773913           0.704348           0.773913   
7           0.739130           0.782609           0.695652           0.747826   
8           0.721739           0.747826           0.678261           0.747826   
9           0.730435           0.756522           0.686957           0.739130   

   mean_test_score  std_test_score  rank_test_score  
0         0.685712        0.019321               10  
1         0.692684        0.026401                9  
2         0.692699        0.007290                8  
3         0.699700        0.031367                7  
4         0.725697        0.023020                4  
5         0.734423        0.027847                2  
6         0.741379        0.030721                1  
7         0.734423        0.030934                2  
8         0.722234        0.025647                6  
9         0.723988        0.024465                5

In [29]:
alist = [10,7]

In [30]:
for a in alist:
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
    dbknnchk = KNeighborsClassifier(n_neighbors = a)
    dbknnchk.fit(X, y)
    db_newpred = dbknnchk.predict(X_test)
    confused = cm(db_newpred, y_test)
    print(str(a), "Neighbors accuracy:", metrics.accuracy_score(y_test, db_newpred))
    print("precision:", metrics.precision_score(y_test, db_newpred, average='weighted'))
    print(confused)

10 Neighbors accuracy: 0.8072916666666666
precision: 0.8025471552257267
[[118  25]
 [ 12  37]]
7 Neighbors accuracy: 0.8177083333333334
precision: 0.8136297565721008
[[117  22]
 [ 13  40]]


### The results from the GridSearch show us the optimal K for our model is 7, with the highest mean test score, yielding more precise and accurate results than our model with a K of 10
